//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLanguage
    {
        public int JobLanguageID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> LangaugeID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Language Language { get; set; }
    }
}
